parameters:

services:
    _defaults:
        public: false

    # Bus
    command_bus:
        class: AFS\BusBundle\Messenger\Bus\CommandBus
        arguments: [ !tagged messenger.commandbus_middleware ]

    event_bus:
        class: AFS\BusBundle\Messenger\Bus\EventBus
        arguments: [ !tagged messenger.eventbus_middleware ]

    AFS\BusBundle\Messenger\Bus\CommandBusInterface:
        alias: command_bus

    AFS\BusBundle\Messenger\Bus\EventBusInterface:
        alias: event_bus

    # Middleware
    messenger.middleware.call_message_handler_command:
        class: AFS\BusBundle\Messenger\Middleware\HandleCommandMessageMiddleware
        arguments: [ '@messenger.handler_resolver' ]
        tags:
            - { name: 'messenger.commandbus_middleware', priority: -10 }

    messenger.middleware.call_message_handler_event:
        class: AFS\BusBundle\Messenger\Middleware\HandleEventMessageMiddleware
        arguments: [ '@messenger.handler_resolver' ]
        tags:
            - { name: 'messenger.eventbus_middleware', priority: -10 }

